name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push 이벤트 발생 시 작동

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i /path/to/your-key.pem ec2-user@${{ secrets.EC2_INSTANCE_PUBLIC_DNS }} << 'EOF'
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install flask
        git pull
        nohup python3 app.py &
        EOF
      env:
        EC2_INSTANCE_PUBLIC_DNS: ec2-18-213-246-238.compute-1.amazonaws.com  # EC2 인스턴스의 공용 DNS
